site_name: LFPH Implementers Forum
theme: 
  name: material
  features:
    - instant
  palette:
    scheme: preference
    primary:
    accent: 
  favicon: img/favicon.ico
  logo: img/lfph-icon-white.svg
repo_name: LFPH
repo_url: https://github.com/lfph/implementers-forum
nav:
  - 'index.md'
  - 'getting-started.md'
  - 'Documentation':
    - 'adoption-and-rollout.md'
    - 'analytics.md'
    - 'equity-and-inclusion.md'
    - 'legal-documents.md'
    - 'verification-codes.md'
    - 'risk-scoring.md'
    - 'test-cases.md'
    - 'user-research.md'
  - 'contributors.md'
extra_css:
  - css/extra.css
extra: 
  social: 
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/lfpubhealth 
google_analytics:
  - UA-82811140-43
  - auto
  
